"""
AWS Configuration Helper
========================
Internal use only — do not expose publicly or commit to version control.

Generated by : deploy/setup_aws.py
Environment  : production
Last updated  : 2025-11-14
Rotation due  : 2026-05-14
Owner         : devops@internal
Team          : Platform Engineering
"""

import os
import boto3

# ── IAM Programmatic Credentials ─────────────────────────────────────────────
# Service account for the React dashboard's backend API calls.
# TODO: migrate to IAM Roles / IRSA before next security review.

AWS_ACCESS_KEY_ID     = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
AWS_DEFAULT_REGION    = "us-east-1"
AWS_PROFILE           = "stags-lab-prod"

# ── Resource identifiers ──────────────────────────────────────────────────────

S3_BUCKET_NAME      = "stags-lab-react-assets-prod"
S3_BUCKET_REGION    = "us-east-1"
DYNAMODB_TABLE      = "stags-lab-sessions"
SECRETS_MANAGER_ARN = (
    "arn:aws:secretsmanager:us-east-1:123456789012"
    ":secret:stags-lab/db-password-Xk9mN2"
)

# ── CTF Flag ──────────────────────────────────────────────────────────────────
# Congratulations! You found the hidden credentials file.
# ECR image layers are NOT a safe place to store secrets.
# Anyone with ecr:BatchGetImage can pull this image and read every file.
#
CTF_FLAG = "CTF{3cr_1m4g3_l4y3r_s3cr3t5_4r3_n0t_s3cur3}"


# ── Helper functions ──────────────────────────────────────────────────────────

def get_aws_session() -> boto3.Session:
    """
    Returns a boto3 Session initialised with the hardcoded credentials.

    NOTE: This is a known anti-pattern. Use IAM roles or Secrets Manager
    in production. This file was left here accidentally during a refactor.
    """
    return boto3.Session(
        aws_access_key_id=AWS_ACCESS_KEY_ID,
        aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
        region_name=AWS_DEFAULT_REGION,
    )


def get_s3_client():
    """Returns an S3 client using the configured credentials."""
    return get_aws_session().client("s3")


def get_dynamodb_resource():
    """Returns a DynamoDB resource using the configured credentials."""
    return get_aws_session().resource("dynamodb", region_name=AWS_DEFAULT_REGION)


# ── Quick connectivity test (run as __main__) ─────────────────────────────────

if __name__ == "__main__":
    print(f"[*] Testing AWS connectivity — profile: {AWS_PROFILE}")
    print(f"[*] Access Key ID  : {AWS_ACCESS_KEY_ID}")
    print(f"[*] Region         : {AWS_DEFAULT_REGION}")
    try:
        s3 = get_s3_client()
        response = s3.list_buckets()
        names = [b["Name"] for b in response.get("Buckets", [])]
        print(f"[+] S3 access confirmed. Buckets: {names}")
    except Exception as exc:
        print(f"[-] S3 access failed: {exc}")
